[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Environment variables will be set in Netlify dashboard
# VITE_SUPABASE_URL = "your_supabase_project_url"
# VITE_SUPABASE_ANON_KEY = "your_supabase_anon_key"